#! /bin/bash
# Convenience script to get around "MESA-LOADER: failed to open iris" error
# seen on some OSes (e.g. Ubuntu 22.04 (Jammy Jellyfish)).

export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
python deskclock.py
